### ISSUE TITLE
Codes are missing

### ISSUE THREAD

**Issue by hforoughmand** [roblanf/sarscov2phylo#23]
The new approach is to keep the tree and update it via for example scripts/add_seqs_to_tree.sh. But the bash script file doesn't contain the code. Is that a problem with the codes or with the github repository? 
Also there is a scripts/add_seqs_to_global_tree.sh which is also only some lines of comments.
Please help me in getting the updated codes.

**Comment by roblanf** [comment]
Hi @hforoughmand, please don't use this repo to build trees of SARS-CoV-2 any more. 

I suggest instead using UShER and matOptimize, which you can find here: https://usher-wiki.readthedocs.io/en/latest/matOptimize.html

**Comment by roblanf** [comment]
I updated the readme to make this clear! 

I also put a link to MAPLE in the readme. Please check that out too - it's another tool built spefically for estimating big trees of SARS-CoV-2.
