### ISSUE TITLE
Global masking VCF

### ISSUE THREAD

**Issue by tseemann** [roblanf/sarscov2phylo#6]
https://github.com/W-L/ProblematicSites_SARS-CoV2

This study suggests masking sites.
Could you support this?
Does it coincide with your filtering etc?

**Comment by roblanf** [comment]
Yep, working on it now. I'm not 100% convinced that all of those sites should be masked, but I'm also keen to make sure that decisions are all evidence-based. So my feeling for now is that I mask all of those sites they suggest, and that anyone (including me) who thinks the masking should differ presents the evidence on their repo. As long as they are receptive to discussion and new evidence, this won't be a problem.

**Comment by roblanf** [comment]
also see https://github.com/roblanf/sarscov2phylo/issues/2

**Comment by roblanf** [comment]
Now done. Latest tree is currently running, so I'll close this once it's finished in ~24h.

But just to note, I mask every site in this file:

https://raw.githubusercontent.com/W-L/ProblematicSites_SARS-CoV2/master/subset_vcf/problematic_sites_sarsCov2.mask.vcf

It also requires the latest pre-release of `goalign`, which I just `wget` (nice solution eh?)

**Comment by roblanf** [comment]
Done. Tree from filtered sequences is in this release: https://github.com/roblanf/sarscov2phylo/releases/tag/6-6-20

**Comment by roblanf** [comment]
Perhaps of interest @tseemann, I thought I'd check to see if masking the additional ~30 sites impacts the branch support. Short answer, it really doesn't seem to.

Here's the distribution of branch support in the tree from 3rd of June (without masking sites)

![image](https://user-images.githubusercontent.com/895251/83960524-f24abb00-a8cc-11ea-9cff-8ae93e305118.png)

And here's the same distribution from 6th of June (after masking sites)

![image](https://user-images.githubusercontent.com/895251/83960538-13131080-a8cd-11ea-8eee-82e95dadfbda.png)

Before masking sites, 34.6% of TBE values are >0.5. After masking sites, this changes to 34.7%. Similarly, before masking sites, 2.6% of TBE values are >0.9. After masking sites, this changes to 2.5%. 

So, as expected, we appear to be masking sites that do little or nothing to help infer the tree.
